//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module7SQLConnectionDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTable
    {
        public decimal Eid { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public decimal DepartmentId { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual DeptTable DeptTable { get; set; }
    }
}
